server:
  port: 10001
logging:
  level: debug
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/openempi?charset=utf8&amp;useUnicode=true&amp;useSSL=false
    username: xuning
    password: openempi
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      pool-name: hikari-pool
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true