spring:
  application:
    name: appTest
  output:
    ansi:
      enabled: always
  http:
    encoding:
      charset: utf-8
      force: true
  profiles:
    active: @profiles.active@
server:
  connection-timeout: 60000