spring:
  application:
    name: DtuDataCenter
  output:
    ansi:
      enabled: always
  http:
    encoding:
      charset: utf-8
      force: true
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#mybatis:
#  mapperLocations: classpath*:mybatis/*Mapper.xml
#  typeAliasesPackage: com.app.dtu.bean.model
server:
  connection-timeout: 60000