server:
  port: 5005
logging:
  level: info
  file: ./log/app.log
spring:
  # Database connection info
  datasource:
    name: dataSource
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://114.116.23.218/fms?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: qwe@w1#gg$v_
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
          idle-timeout: 10000
          maximum-pool-size: 40
          pool-name: hikari-pool
          connection-timeout: 8000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  # Message queue config
  rabbitmq:
    host: 114.116.23.218
    port: 5672
    username: admin
    password: xuning!
    listener:
      prefetch: 1
      transaction-size: 1
  # Redis cache config
#  redis:
#    host: 114.116.23.218
#    database: 0
#    port: 6379
#    timeout: 0
#    pool:
#      max-active: 50
#      max-idle: 50
#      min-idle: 0
#      max-wait: 10

  # Auto active produce env
  profiles:
    active: produce