server:
  port: 5005
logging:
  level: info
  file: ./log/app.log
spring:
  datasource:
    name: dataSource
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://118.89.240.60/fms?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: qwe@w1#gg$v_
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
          idle-timeout: 6000
          maximum-pool-size: 10
          pool-name: hikari-pool
          connection-timeout: 6000
  rabbitmq:
    host: 59.110.9.17
    port: 5672
    username: admin
    password: xuning!
    listener:
      prefetch: 10
      retry:
        enabled: true
      transaction-size: 1
    cache:
      connection:
        size: 50000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  profiles:
    active: produce